services:
  mongodb:
    image: mongo:latest
    container_name: dev_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev123
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123
      ME_CONFIG_MONGODB_URL: mongodb://dev:dev123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev123

  redis:
    image: redis:latest
    container_name: dev_redis
    command: ["redis-server", "--requirepass", "dev123"]
    ports:
      - "6379:6379"
